runtime: /usr/bin/crun
runpath: /var/run/dbox
containers_path: /var/lib/dbox/containers
volumes_path: /var/lib/dbox/volumes

# Optional custom registries
registries:
    alpine: docker.io/library/alpine
    ubuntu: docker.io/library/ubuntu
    debian: docker.io/library/debian
    archlinux: docker.io/library/archlinux
    fedora: docker.io/library/fedora
    kali: docker.io/kalilinux/kali-rolling

