runtime: /usr/bin/crun
runpath: /var/run/dbox
containers_path: /var/lib/dbox/containers
volumes_path: /var/lib/dbox/volumes

# Optional custom registries
# Map registry names to their URLs (for private registries)
registries:
    # Example for a private registry
    # myregistry: registry.example.com:5000
    ghcr: ghcr.io
    # quay: quay.io

